name: flower_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_localization: ^0.3.0
  flutter_translate: ^4.1.0
  flutter_svg: ^2.0.16
  http: ^1.2.2
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  provider_base_tools: ^0.1.6
  responsive_framework: ^1.5.1
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  intl_utils:
  firebase_core: ^3.10.1
  firebase_data_connect: ^0.1.2+7
  firebase_auth: ^5.4.1
  lottie:
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  awesome_snackbar_content: ^0.1.5
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/l10n/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app.png"
  adaptive_icon_background: "assets/images/icon_app.png"
  adaptive_icon_foreground: "assets/images/icon_app.png"

flutter_intl:
  enabled: true
